export const typreData = [
    {
        id: "1",
        city: "Dubai",
        fleet_name: "United",
        tyreSize: "385/65R22.5",
        pr: "18",
        pattern: "SSR1",
        brand: "MRF",
        testStartDate: "23-Jan-23",
        testEndDate: "23-Mar-23",
        nsdOnFinish: "",
        reasonOfTyreRemoval: "Burst",
        projectTyreLife: "74713",
        actualLife: "50000",
    },
    {
        id: "2",
        city: "Dubai",
        fleet_name: "United",
        tyreSize: "385/65R22.5",
        pr: "18",
        pattern: "SSR1",
        brand: "MRF",
        testStartDate: "25-Feb-23",
        testEndDate: "23-Mar-23",
        nsdOnFinish: "",
        reasonOfTyreRemoval: "Burst",
        projectTyreLife: "74666",
        actualLife: "60000",
    },
    {
        id: "3",
        city: "Dubai",
        fleet_name: "United",
        tyreSize: "385/65R22.5",
        pr: "18",
        pattern: "SSR1",
        brand: "MRF",
        testStartDate: "23-Jan-23",
        testEndDate: "23-Mar-23",
        nsdOnFinish: "",
        reasonOfTyreRemoval: "Burst",
        projectTyreLife: "76342",
        actualLife: "55000",
    }
]
